---
- name: ansible project
  hosts: all
  become: yes
  remote_user: <your-username>

  handlers:
    - import_tasks: handlers/main.yml

  roles:
    - ssh
    - apache
    - mysql
    - php
    - firewall
    - monitoring
    - alertmanager


    

  
