- name: installing OpenSSH
  apt:
    name: openssh-server
    state: present
    update_cache: yes 

- name: Create .ssh directory if it doesn't exist
  file:
    path: "/home/navyasattineni/.ssh"
    state: directory
    owner: "navyasattineni"
    group: "navyasattineni"
    mode: '0700'          # Important for security

- name: Add your SSH public key for remote access
  authorized_key:
    user: "navyasattineni"
    key: "{{ lookup('file', '~/.ssh/ansible_key.pub') }}"