- name: installing OpenSSH
  apt:
    name: openssh-server
    state: present
    update_cache: yes 

- name: Create .ssh directory if it doesn't exist
  file:
    path: "home/{{ ansible_user }}/.ssh"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0700'          # Important for security

- name: Add your SSH public key for remote access
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', ssh_public_key_path) }}"
