# This task installs and configures UFW to allow traffic for Apache, Prometheus, Node Exporter, and Alertmanager.
- name: Ensure UFW is installed
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: Allow Apache traffic in UFW
  ufw:
    rule: allow
    name: "Apache Full"

- name: Enable UFW firewall
  command: ufw --force enable     # --force bypasses interactive confirmation
  become: yes

- name: Allow Prometheus port
  ufw:
    rule: allow
    port: 9090
    proto: tcp

- name: Allow Node Exporter port
  ufw:
    rule: allow
    port: 9100
    proto: tcp

- name: Allow Alertmanager port
  ufw:
    rule: allow
    port: 9093
    proto: tcp
